import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { CartProvider } from "./components/Context/CartContext";
import { AuthProvider } from "./components/Context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <CartProvider>
          <body className="flex flex-col min-h-screen">
            <Navbar />
            <div className="flex-grow p-3">{children}</div>
            <Footer />
          </body>
        </CartProvider>
      </AuthProvider>
    </html>
  );
}
